### ISSUE TITLE
CosmosDB Client does not create Indexing Policy properly

### ISSUE THREAD

**Issue by denis-huber-qaware** [Azure/azure-cosmosdb-java#93]
**Describe the bug**
I am using `com.microsoft.azure:azure-cosmosdb:2.4.4`. When I send a request to create a collection with `IndexingPolicy`, the Indexing Policy is not created in Cosmos DB. When I use `com.microsoft.azure:azure-cosmosdb:2.3.1` the Indexing Policy is created in Cosmos DB.

**To Reproduce**
I created a minimal example that reproduces the bug: https://github.com/denis-huber-qaware/cosmosdb-indexing-policy. The README contains the steps to run the program.

Here are the relevant lines:
```java
DocumentCollection documentCollection = new DocumentCollection();
documentCollection.setId(COLLECTION);
IndexingPolicy indexingPolicy = new IndexingPolicy();
indexingPolicy.setIndexingMode(IndexingMode.Consistent);
IncludedPath includedPath = new IncludedPath();
includedPath.setPath("/*");
Index numberIndex = Index.Range(DataType.Number, -1);
Index stringIndex = Index.Range(DataType.String);
includedPath.setIndexes(Arrays.asList(numberIndex, stringIndex));
indexingPolicy.setIncludedPaths(Collections.singletonList(includedPath));
documentCollection.setIndexingPolicy(indexingPolicy);

ResourceResponse<DocumentCollection> response = client.createCollection(String.format("/dbs/%s", DATABASE), documentCollection, null).toBlocking().single();
```
Source: https://github.com/denis-huber-qaware/cosmosdb-indexing-policy/blob/master/src/main/java/com/example/demo/App.java#L56

**Expected behavior**
I expect, that the Indexing Policy is created with the following value in the Data Explorer in the Microsoft Azure's webapp (https://portal.azure.com):
```yaml
{
    "indexingMode": "consistent",
    "automatic": true,
    "includedPaths": [
        {
            "path": "/*",
            "indexes": [
                {
                    "kind": "Range",
                    "dataType": "Number",
                    "precision": -1
                },
                {
                    "kind": "Range",
                    "dataType": "String",
                    "precision": -1
                }
            ]
        }
    ],
    "excludedPaths": [
        {
            "path": "/\"_etag\"/?"
        }
    ]
}
```

**Actual behavior**
I receive the following Indexing Policy in the webapp (https://portal.azure.com):
```yaml
{
    "indexingMode": "consistent",
    "automatic": true,
    "includedPaths": [
        {
            "path": "/*",
            "indexes": []
        }
    ],
    "excludedPaths": [
        {
            "path": "/\"_etag\"/?"
        }
    ]
}
```

**Environment summary**
SDK Version: 2.4.4
Java JDK version: 
```
openjdk version "1.8.0_201"
OpenJDK Runtime Environment (build 1.8.0_201-b09)
OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)
```
OS Version (e.g. Windows, Linux, MacOSX): Linux
